### ISSUE TITLE
Keep and eye on publish workflow

### ISSUE THREAD

**Issue by dianjuar** [bikecoders/ngx-deploy-npm#130]
We've been facing a lot of errors in the publishment workflow; #129 Seems to be the end of our headaches.

Leave this issue open remind ourselves to keep watching that process

**Comment by dianjuar** [comment]
It seems to be working correctly, with the exception of the `last-release` tag

![image](https://user-images.githubusercontent.com/7026066/146211838-278a66f1-4aa5-4043-8577-138957b4fe0f.png)

**Comment by marsicdev** [comment]
Hi @dianjuar is this issue the reason why there is a problem with NPM registry https://www.npmjs.com/package/ngx-deploy-npm ?

**Comment by antonio-rodrigues** [comment]
https://www.npmjs.com/package/ngx-deploy-npm
`{ error: "Service Unavailable" }`

And of course, it fails to retrieve the version also at https://yarnpkg.com/package/ngx-deploy-npm.

**Comment by dianjuar** [comment]
No, the scope of this issue is on CI.

npm is down. I couldn't fetch common packages like react, angular or @nrwl/cli

https://twitter.com/npmstatus/status/1471147122892279810

**Comment by dianjuar** [comment]
The commit generated on release is asking for deployment. This behavior is not wanted

https://github.com/bikecoders/ngx-deploy-npm/actions/runs/1675401613

**Comment by dianjuar** [comment]
Fixes introduced:
- `last-release` tag movement to last commit. https://github.com/bikecoders/ngx-deploy-npm/issues/130#issuecomment-994885318 
- Asking for deployment on release commit. https://github.com/bikecoders/ngx-deploy-npm/issues/130#issuecomment-1008487066

Since we can't test this right away, keep this issue open to tracking these fixes.

**Comment by dianjuar** [comment]
`last-release` tag movement to last commit problem, fixed 🟢 
Do not run publishment workflow on autogenerated commits on master, not working ❌

**Comment by dianjuar** [comment]
Do not run publishment workflow on autogenerated commits on master, solved 🟢

https://github.com/bikecoders/ngx-deploy-npm/actions/runs/1679990378
