### ISSUE TITLE
fix required: throw an error if build fails

### ISSUE THREAD

**Issue by JohannesHoppe** [bikecoders/ngx-deploy-npm#16]
see https://github.com/angular-schule/angular-cli-ghpages/issues/74

The deploy builder should stop the deploying process if the build breaks.

Broken:
https://github.com/bikecoders/ngx-deploy-npm/blob/f93ab78802b5cd11a634157ffc57643ba51c3431/src/deploy/actions.ts#L41

Fixed:
https://github.com/angular-schule/ngx-deploy-starter/blob/f4d126c186c17f391d966d69e9526fdb1cd9908e/src/deploy/actions.ts#L51-L53

**Comment by JohannesHoppe** [comment]
Please also note release v0.0.3 of npx-deploy-starter, where I made a number of small improvements. 😃

**Comment by dianjuar** [comment]
Sorry for the delay 😅

Fix released under the [version 1.4.3](https://www.npmjs.com/package/ngx-deploy-npm/v/1.4.3)

**Comment by dianjuar** [comment]
FYI @edbzn
