### ISSUE TITLE
Auto increment version?

### ISSUE THREAD

**Issue by floinay** [bikecoders/ngx-deploy-npm#234]
I can enable auto increment version? 
Example:
{
"version": "2.0.0"
}
nx deploy library --auto-increment
{
"version: "2.0.1"
}

**Comment by floinay** [comment]
I found answer on the docs 😊

**Comment by dianjuar** [comment]
> I found the answer on the docs 😊

Yes, we have addressed this problem, and we decided to put it in the [docs](https://github.com/bikecoders/ngx-deploy-npm#version-generation).

In case someone is wondering:
> This deployer doesn't bump or generate a new package version; here, we care about doing one thing well, publish your libs to NPM. You can change the version package at publishment using the [--package-version](https://github.com/bikecoders/ngx-deploy-npm#--package-version) option.
> 
> We strongly recommend using [@jscutlery/semver](https://github.com/jscutlery/semver) to generate your package's version based on your commits automatically. When a new version is generated you can specify to publish it using ngx-deploy-npm.
> 
> We use `@jscutlery/semver` here on `ngx-deploy-npm` to generate the package's next version, and we use `ngx-deploy-npm` to publish that version to NPM. Yes, it uses itself, take a look by yourself [ngx-deploy-npm/project.json](https://github.com/bikecoders/ngx-deploy-npm/blob/master/packages/ngx-deploy-npm/project.json#L55-L67)
