### ISSUE TITLE
Fix deployment for v11

### ISSUE THREAD

**Issue by mgechev** [bikecoders/ngx-deploy-npm#27]
Because we removed some experimental APIs (promoted them as public in v11), the deployment builder no longer works.

It should be relatively easy to migrate. Here's an example from AngularFire https://github.com/angular/angularfire/pull/2643.

**Comment by dianjuar** [comment]
@mgechev I found a problem here, hope you can lead me with it.

I was following [Angular Fire PR](https://github.com/angular/angularfire/pull/2643) that you brought, I see that they use [`context.getTargetOptions`](https://github.com/angular/angularfire/pull/2643/files#diff-3ec0840be66029e0f049b9b68fd66805766a1ba221d1c7afe66e7dc8dee2592eR129) to get the project's `outputPath` but for a library that property is not being returned.

Do you know if to get the `outputPath` for a library we need to use another method different than `.getTargetOptions`?

---

I think I have a workaround but I feel it's too nasty :vomiting_face:, `.getTargetOptions` returns the path for the file `projects/{MY-LIB-NAME}/ng-package.json` and that file has the following structure.

```json
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/{MY-LIB-NAME}",
  "lib": {
    "entryFile": "src/public-api.ts"
  }
}
```

I can read that file, and get the `dest` property to get the `outPath` that I need. What do you think about this?

**Comment by mgechev** [comment]
Doesn't sound that terrible to me, if you can always resolve the location of the library package configuration.

The only risky thing here would be if ng-packagr changes their configuration file.

**Comment by dianjuar** [comment]
@mgechev I'm going to implement the solution that I mentioned to have V11 support ASAP, I think is the only way to go with this.

I wonder if the `BuilderContext.getTargetOptions` should give me those options or the function is only limited to get information that is on the `angular.json` and I'm forced to go with the `ng-package.json` to get more information about the library that I'm building?

**Comment by mgechev** [comment]
You could open an issue in [angular-cli](https://github.com/angular/angular-cli) and get more feedback there from the CLI team.

**Comment by JohannesHoppe** [comment]
It also wasn't my best idea to introduce the `--configuration` param. 😅 
I think we need a breaking change to get out of this situation. I'm right now trying to correct this for angular-cli-ghpages.

See
https://github.com/angular/angularfire/issues/2063#issuecomment-570518883
https://github.com/angular-schule/ngx-deploy-starter/issues/1#issuecomment-605646481

**Comment by dianjuar** [comment]
I am having a good family time 😄.
I will work on this over the weekend

**Comment by JohannesHoppe** [comment]
I will port back all changes to the starter, soon.

**Comment by dianjuar** [comment]
Thank you @mgechev for let me know about this problem so early.

The fix is ready under the version [ngx-deploy-npm@1.3.1](https://www.npmjs.com/package/ngx-deploy-npm/v/1.3.1) 🚀
