### ISSUE TITLE
Schema wants OTP to be a string, but it's really a number

### ISSUE THREAD

**Issue by Phault** [bikecoders/ngx-deploy-npm#351]
Providing the OTP by passing it through the CLI fails as the value provided is coerced into a number, rather than staying a string like the executor schema expects. 

```shell
>  nx run utilities:deploy-npm --otp=634119
Property 'otp' does not match the schema. '634119' should be a 'string'.
```

As a workaround, I've patched the schema to expect a number and it works just fine.

Using Nx 14.3.6 and ngx-deploy-npm 4.1.2.

**Comment by dianjuar** [comment]
What about:

```diff
- nx run utilities:deploy-npm --otp=634119
+ nx run utilities:deploy-npm --otp='634119'
```

I'm not entirely familiar with the OTP parameter. Is the OTP parameter a number?

**Comment by dianjuar** [comment]
If the right path is changing the OTP type to a number, not a string, we are open to receiving the contribution.

A good starting point is changing the type of the OTP parameter on:

- https://github.com/bikecoders/ngx-deploy-npm/blob/main/packages/ngx-deploy-npm/src/executors/deploy/schema.json#L32
- https://github.com/bikecoders/ngx-deploy-npm/blob/main/packages/ngx-deploy-npm/src/executors/deploy/schema.d.ts#L25

**Comment by dianjuar** [comment]
I was able to make it run with 
 --dry-run

```diff
- nx run utilities:deploy-npm --otp=634119
+ npx nx deploy node-lib1 --otp "'634119'"
```

But I still it can be improved by changing the type to a number or string
