### ISSUE TITLE
Implement CI to this project, only Continuous Integration, PR analysis

### ISSUE THREAD

**Issue by dianjuar** [bikecoders/ngx-deploy-npm#37]
It's time to have a CI to run the test, build and, all that cool stuff that a CI brings. Let's start giving small steps implementing for the beginning only Continuous Integration to analyze the PR's after its integration to master. 

This will found a solid ground to embrace more complex stuff like continuous deployment or continuous inspection with [SonarQube](https://www.sonarqube.org/).

**Comment by dianjuar** [comment]
@JohannesHoppe I see that you have experimented with GitHub actions on some of your projects, could you give your opinion of using GitHub Actions over CircleCI?

I have plenty of experience with CircleCI, I know the product and I feel comfortable using it, it's really cool and powerful. I have no experience with GitHub Actions though, I would like to hear how is your experience with the product.

**Comment by JohannesHoppe** [comment]
It totally depends. With CircleCi, you can take any Docker image as a base and SSH into it for debugging This is great and is not available on GitHub actions. However, you have to start paying money pretty soon.

GitHub actions offers [a huge marketplace](https://github.com/marketplace?type=actions). If there is already a helpful tool there, that might help with the decision. I have to pay for the org anyway, so it doesn't matter from a price standpoint.

In general. I have no idea. They are both excellent... 😅

**Comment by dianjuar** [comment]
Github actions Rocks 🚀

**Comment by JohannesHoppe** [comment]
# 🎉
