### ISSUE TITLE
[ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stderr maxBuffer length exceeded

### ISSUE THREAD

**Issue by dgonzalezr** [bikecoders/ngx-deploy-npm#401]
Hi there, I have a [Stenciljs](https://stenciljs.com/) web component library set up on my Nx monorepo, and whenever I try to deploy (publish) the library I get the following error:

![CleanShot 2022-11-02 at 14 25 25](https://user-images.githubusercontent.com/328492/199489238-6f8cd2cf-457a-4284-82e1-68144e48d7a6.png)

If I manually run npm publish over the library build, it works as expected. Any idea what can be the reason for `ngx-deploy-npm` failing? 

I want to mention that it runs ok in another library under the same monorepo (a react wrapper library for the web component library discussed before).

**Comment by dgonzalezr** [comment]
Hi, @dianjuar thank you for your reply. Regarding your questions, please see below:

* Which version of `ngx-deploy-npm` do you have?

I'm using the latest version but unfortunately, the logs do not say much about the error.

![CleanShot 2022-11-02 at 18 05 25](https://user-images.githubusercontent.com/328492/199540865-db03d231-0d73-422a-aefc-783be4ef21d0.png)

* Can you share the Nx Plugin that creates the library you are trying to publish?

The plugin used is [@nxext/stencil](https://nxext.dev/docs/stencil/overview.html)

* Is this on a public repo where I can take a look?

Unfortunately not, but I'm ok to grant you access for a couple of days if that would be fine for you as well 🙂

**Comment by dgonzalezr** [comment]
By the way, the library includes tons of SVG files (for an icon component), could that be the reason why `ngx-deploy-npm` fails? But again, running `npm publish` on the build directory of the library works fine 🤔

**Comment by dianjuar** [comment]
I have access now.

I took a look, and everything seems to be in order.
I'm going to debug the publish-beta operation on your code base to see step by step what is going on.

I'll try to do that today at night.

**Comment by dgonzalezr** [comment]
> I have access now.
> 
> I took a look, and everything seems to be in order. I'm going to debug the publish-beta operation on your code base to see step by step to watch more in-depth what could be the reason.
> 
> I'll try to do that today at night.

Thanks a lot @dianjuar 🙌🏼

**Comment by dianjuar** [comment]
@dgonzalezr, to isolate the problem, can you create an empty publishable library with [@nxext/stencil](https://nxext.dev/docs/stencil/overview.html) and try to publish it to NPM and see that everything runs smoothly?

With `--dry-run` is just fine.

**Comment by dgonzalezr** [comment]
Hi @dianjuar, I've created an Nx workspace from scratch with a dummy Stencil library and the publish seems to work as expected:

![CleanShot 2022-11-03 at 12 39 37](https://user-images.githubusercontent.com/328492/199700534-91f350cd-cb38-481e-92cd-50d5dde1ae04.png)

My guess is that the number of files could be the issue since, as I mentioned before, we have a lot of SVG files included in one of our components:

![CleanShot 2022-11-03 at 12 41 56](https://user-images.githubusercontent.com/328492/199700795-dcb07bcc-7589-41b4-b1c6-26daf0c4be46.png)

**Comment by dgonzalezr** [comment]
Yep, I can confirm the issue, the moment I added into the new empty stencil library the same script that downloads all the SVG files (from a Github source) into the repo and built the project successfully, `ngx-deploy-npm` fail.

![CleanShot 2022-11-03 at 12 57 09](https://user-images.githubusercontent.com/328492/199703680-1e11830b-b0c2-4401-9f32-bda6f7948052.png)

**Comment by dgonzalezr** [comment]
@dianjuar you can find the repo here:
https://github.com/dgonzalezr/stencil-nx-monorepo

Try to build the library without the `assets` folder in the my-component.tsx:
https://github.com/dgonzalezr/stencil-nx-monorepo/blob/main/libs/bee-q/src/components/my-component/my-component.tsx#L5
and run the `npm run publish` command... Do the same enabling the assets folder, building the library, and run the publish script command again.

**Comment by dianjuar** [comment]
@dgonzalezr, you forgot to upload the [SVG](https://github.com/dgonzalezr/stencil-nx-monorepo/tree/main/libs/bee-q/src/components/my-component/svg) files

I can't replicate the error

**Comment by dgonzalezr** [comment]
@dianjuar there's a comment on the [my-component.tsx](https://github.com/dgonzalezr/stencil-nx-monorepo/blob/main/libs/bee-q/src/components/my-component/my-component.tsx#L5):

![CleanShot 2022-11-03 at 16 53 14](https://user-images.githubusercontent.com/328492/199754683-4490128a-b74b-448a-9e20-dbbf451c8d29.png)

Uncomment that line to replicate the error, the SVGs are downloaded within an Nx executor, so if your run:

```
npm run build
```

The executor will run first.

**Comment by dgonzalezr** [comment]
@dianjuar did you manage to replicate the issue? 🙂

**Comment by dianjuar** [comment]
I was able to replicate it

![image](https://user-images.githubusercontent.com/7026066/199864958-b80a52bb-4cc3-4e42-9580-363d7a6fe454.png)

Let me debug it.

**Comment by dianjuar** [comment]
I found the problem.

`npm publish` creates a list of all the files in your bundle. The number of files in your bundle is large. So large that my terminal couldn't print it all, I couldn't scroll across the output because it got cut.

We execute the `npm publish` command using [`child_process.exec`](https://github.com/bikecoders/ngx-deploy-npm/blob/main/packages/ngx-deploy-npm/src/executors/deploy/engine/engine.ts#L33) and a particularity that `child_process.exec` has is when the size of the stdout is bigger than the default amount of buffer it produces an error.

That's why you are able to execute the command without problems, but `ngx-deploy-npm` don't.

See node `child_process.exec` [documentation](https://nodejs.org/api/child_process.html#child_processexeccommand-options-callback)
> maxBuffer `<number>` Largest amount of data in bytes allowed on stdout or stderr. If exceeded, the child process is terminated and any output is truncated. See caveat at [maxBuffer and Unicode](https://nodejs.org/api/child_process.html#maxbuffer-and-unicode). Default: 1024 * 1024.

---

The solution seems to be using [`child_process.spawn`](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options) instead. They have events instead of a buffer to expose the stdout.

I would work on the fix.

**Comment by dgonzalezr** [comment]
Thank you @dianjuar for looking into it 🙂

**Comment by dianjuar** [comment]
@dgonzalezr an idea that I have, as hot fix. I can increase the buffer to its maximum to see if that's enough to allow you publish.

I can do that very quickly, so you'll be able to move forward. In the meantime, I'll be working on the fix described above.

It works for you?

**Comment by dgonzalezr** [comment]
> @dgonzalezr an idea that I have, as hot fix. I can increase the buffer to its maximum to see if that's enough to allow you publish.
> 
> I can do that very quickly, so you'll be able to move forward. In the meantime, I'll be working on the fix described above.
> 
> It works for you?

Sure @dianjuar let's give it a try :)

**Comment by dianjuar** [comment]
@dgonzalezr using V4.3.2 you will be able to publish your package.

I'll be working on a more permanent fix

**Comment by dgonzalezr** [comment]
> @dgonzalezr using V4.3.2, you will be able to publish your package.
> 
> Let's leave this issue open while I work on a more permanent fix. Please leave your public repo alive so I can have a real-world scenario for testing

@dianjuar working as expected, thanks a lot 🙌🏼 🙂

**Comment by dianjuar** [comment]
@dgonzalezr You can find the permanent fix on V4.3.5

Thank you for reporting your problem.
It allows us to make ngx-deploy-npm even better 💪
