### ISSUE TITLE
Crash on windows for version 4.3.5

### ISSUE THREAD

**Issue by Jejuni** [bikecoders/ngx-deploy-npm#418]
When upgrading to version 4.3.5 from 4.3.4 the `npm publish` part of `nx deploy my-lib` now crashes with the following error:

```
An error occurred!
Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Error when trying to publish the library
```

Version 4.3.4 works as expected.
Not sure about other operating systems.

**Comment by dianjuar** [comment]
@Jejuni @megajin on v4.3.6, we fix the problem.
Try it and let us know 😄 

---

Also, we include Windows platform to run our test set (unit and e2e).
Now we **guarantee** that everything will run smoothly on that OS.

https://github.com/bikecoders/ngx-deploy-npm/actions/runs/3510844946

![image](https://user-images.githubusercontent.com/7026066/202945991-4cd3df34-16b3-43f8-a41d-d9c84a33b616.png)

**Comment by Megajin** [comment]
@dianjuar can confirm that  v4.3.6 fixed the `Error: spawn npm ENOENT`. 🥳🎉

**Comment by Jejuni** [comment]
@dianjuar Can also confirm it works! 🎉
