### ISSUE TITLE
Pluguin not working on Angular Workspace 

### ISSUE THREAD

**Issue by dianjuar** [bikecoders/ngx-deploy-npm#467]
We decided to remove on [#454](https://github.com/bikecoders/ngx-deploy-npm/issues/454#issuecomment-1402614502) the Angular E2E tests as required on the Publish CI Pipeline to unblock the issue.

This issue is to keep an eye on Nx for the [fix](https://github.com/nrwl/nx/issues/14413) to:

- Continuing offering support to Angular Workspaces
- Bring back the Angular E2E tests as mandatory on the publish CI pipeline once it gets solved.

**Comment by dianjuar** [comment]
The Nx team may not provide stable compatibility with AngularCLI workspaces. See https://github.com/nrwl/nx/issues/14413#issuecomment-1446732530.

They recommend using Angular CLI DevKit to make it run on Angular CLI workspaces. That put us in a difficult position; we need to support two workspaces in parallel to be fully compatible and stable with AngularCLI workspaces. That seems challenging due to the amount of work that it would require.

**Comment by dianjuar** [comment]
@edbzn I would like to have your input on this problem.

**Comment by edbzn** [comment]
@dianjuar I agree, it's already hard to keep compatibility between different Nx versions (even minor versions), so keeping Angular CLI compatibility is very time-consuming and bug prone. However it depends on your users, are they using more Nx or Angular CLI? If Angular CLI is important for your users you could point to old an ngx-deploy-npm version that might still be compatible with Angular CLI, or even provide fixes/updates to your old branches that still run on Angular CLI, but it means managing two branches that runs on different technologies, it's not ideal.

**Comment by dianjuar** [comment]
I am still determining the percentage of users using this plugin in an Angular Workspace, but in a quick look, apparently, more users are using Nx.

If the AngularCLI workspace users are low, **I would consider deprecating AngularCLI Workspaces.**

For science and fun, I want to create a script based on the [GitHub dependent list](https://github.com/bikecoders/ngx-deploy-npm/network/dependents) stats to determine the portion of users on each workspace. That would give an idea of the number of users that would be affected and if it's a good idea to deprecate the AngularCLI Workspaces compatibility.

---

Recently I saw that the [Nx Console](https://twitter.com/dzhavatushev/status/1638287266253619201?cxt=HHwWgoC-kdblrrwtAAAA) is removing its compatibility with AngularCLI workspaces, so I don't see a bad idea doing the same.

**Comment by dianjuar** [comment]
We can think about a potential plugin name change since the `ngx` prefix is not relevant anymore.

https://twitter.com/edbzn/status/1689916532221001728

**Comment by dianjuar** [comment]
Close using #570.

More information in version 8 release [blog post](https://dev.to/dianjuar/whats-coming-to-ngx-deploy-npm-v8-23gn)
