### ISSUE TITLE
Open version range on dependencies for the published package

### ISSUE THREAD

**Issue by samuelfernandez** [bikecoders/ngx-deploy-npm#470]
Right now the published package uses fixed version for `@nrwl/devkit`, as of today it is [`"15.6.2"`](https://github.com/bikecoders/ngx-deploy-npm/blob/main/packages/ngx-deploy-npm/package.json#L14).

When working with the new npm approach to peer dependencies, installation fails if trying to install for example `@nrwl/devkit@15.6.3`. Ideally the semver requirement for any package would allow at least minor versions as compatible.

Would it be possible, please, to adjust that dependency and make it `"@nrwl/devkit": "^15.6.2"` for the published package? That would allow consumers more flexibility with the peer dependencies.

Thanks for considering! Happy to send a PR

**Comment by dianjuar** [comment]
It is a great idea.

I don't quite understand what you said about
> new npm approach to peer dependencies

I would like to understand your problem fully to provide the best solution.

**Comment by samuelfernandez** [comment]
To repro the issue, create an nx workspace with the very last version, as of today 15.6.3. Trying to install ngx-deploy-nombre will fail because of unmet dependencies.

As a library that depends on having a Nx project, coexisting with that dependency, it would be expected that it would use peerDependencies to depend on @nrwl/devkit. Explanation: https://stackoverflow.com/a/34645112 or https://blog.bitsrc.io/understanding-peer-dependencies-in-javascript-dbdb4ab5a7be

Also, Nx JS executor uses by default this approach as you can see here https://nx.dev/packages/js/executors/tsc#buildableprojectdepsinpackagejsontype

My comment on peerDependencies refers to the breaking change that npm v7 introduced. Before incompatibilities displayed a warning, now they are errors. https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies

Finally, best practices for library authors are to use the minimum required version of the peer library, and be as loose as possible in terms of supported range. Usually that means staying within the same major version. Reference here, point 6 https://medium.com/@jacob.h.page/common-npm-mistakes-51bf8989079f

Your library does a great job because you have event tests against the @next version, which adds yet another safe net for future versions.

Hope this long explanation makes sense, happy to develop further any of the points

**Comment by samuelfernandez** [comment]
BTW this is the error log that triggered the issue https://github.com/nx-squeezer/squeezer/pull/386#issuecomment-1407342051

**Comment by dianjuar** [comment]
@samuelfernandez, It does.
I thought that I'd nailed the concept of peer dependency. Now I see that your explanation could expand my idea even more.

Now I understand better why [@jscutlery/semver](https://github.com/jscutlery/semver/blob/main/packages/semver/package.json#L23) does that (they are outstanding).

With that, I also could provide compatibility to previous Nx (like 14) if I understand correctly if this plugin doesn't have differences between 14~15.

I want to read all your references to gain confidence for the next ngx-deploy-npm move.

**Comment by dianjuar** [comment]
@samuelfernandez happy to see your contribution to this.

Thank you so much for bringing this up. This definitely will expand my experience and knowledge.

**Comment by dianjuar** [comment]
@edbzn I would appreciate your input on this.

**Comment by samuelfernandez** [comment]
> With that, I also could provide compatibility to previous Nx (like 14) if I understand correctly. I believe it's possible if this plugin doesn't have differences between 14~15.

Exactly! That would be much useful. To make sure it'd work, you'd likely need a matrix of integration tests with all the versions you would support.

The recommended approach would be:

* Allow the minimum dependency that the library is compatible with
* When and old version needs to become not supported, do it only in a major version release with a breaking change. This could happen for example if there is a new feature that you will need from `nrwl` that is not present in past versions.
* Support only within the current major version of the dependency, in your case `@nrwl/devkit@^15.0.0`. The reason is that you can't guarantee it will work with `v16`. When it is released, if the tests pass then you can always extend the compatible range manually.
* The integration test matrix could potentially include: oldest supported version (`14.0.0`), current major version on its initial release (`15.0.0`), latest (current, `15.6.2`), next (potentially `16.0.0-beta`)

I'll send a PR. By the way, congratulations for your unit and integration test suit, it is just amazing! 🚀

**Comment by edbzn** [comment]
Hi there, yeah we use peer dependencies and major range `^15.0.0` in @jscutlery/semver, I kind of manage @nrwl/devkit version just like I would manage @angular/core version for an Angular library.

**Comment by samuelfernandez** [comment]
PR https://github.com/bikecoders/ngx-deploy-npm/pull/473
