### ISSUE TITLE
Setting registry not being reflected from nx executor options

### ISSUE THREAD

**Issue by ozee** [bikecoders/ngx-deploy-npm#499]
I am trying to use the `registry` option to define our private npm repository but it seems like no matter what I do, it doesn't recognize that the option is being set. I have also tried setting it via `$HOME/.npmrc` prior to running the nx deploy script both as a scoped registry and a catch-all. I also have my publishConfig set in my package.json that is in the dist folder being deployed but I think that is also ignored or being overwritten. The strange part is that it is getting set somewhere because our proxy the npm registry is being set, but I am unable to publish to that, we have an internal url for publishing to. Here is the relevant nx target:

```json
"deploy": {
  "executor": "ngx-deploy-npm:deploy",
  "options": {
    "access": "public",
    "dryRun": true,
    "noBuild": true,
    "distFolderPath": "dist/packages/somePackage/",
    "registry": "https://****-internal-npm/"
  }
},
```

Any help would be greatly appreciated!

**Comment by ozee** [comment]
Thanks for the quick response @dianjuar! We actually use that same template internally, haha, I should have filled out the information for throughly.

### Current Behavior

The registry isn't set whenever you define it in options.

### Expected Behavior

That whenever you define the registry in the option that it sets that registry, overwriting other places where it could have pulled from.

### GitHub Repo

I don't have a public repo currently that I can show, however I think that you may be onto something above.

### Steps to Reproduce

Try to publish and the deploy packages, gets another registry location.

### Nx Report

```sh
   Node : 16.19.1
   OS   : darwin arm64
   npm  : 8.19.3
   
   nx                      : 15.8.6
   @nrwl/js                : 15.8.6
   @nrwl/jest              : 15.8.6
   @nrwl/linter            : 15.8.6
   @nrwl/workspace         : 15.8.6
   @nrwl/cli               : 15.8.6
   @nrwl/cypress           : 15.8.6
   @nrwl/devkit            : 15.8.6
   @nrwl/eslint-plugin-nx  : 15.8.6
   @nrwl/nx-plugin         : 15.8.6
   @nrwl/storybook         : 15.8.6
   @nrwl/tao               : 15.8.6
   @nrwl/vite              : 15.8.6
   @nrwl/nx-cloud          : 15.3.5
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @jscutlery/semver       : 2.30.1
   @nxkit/style-dictionary : 2.3.0
   ngx-deploy-npm          : 5.2.0
```

### Additional Information

The output from our command `nx deploy YOUR_LIB` is success until literally the final step of the publish where it cites a different registry from what I tried to define.

Some background, we do set the registry earlier in our action to our public npm-proxy for running `npm i` within our workflow inside our organization. I think that locally it may be referring to my `$HOME/.npmrc` directory when running a dry-run. I think that I will try adding a `.npmrc` to each component to see if that does anything different.

**Comment by dianjuar** [comment]
Can we see the output of the `npx nx deploy YOUR_LIB --dry-run` ?

**Comment by dianjuar** [comment]
The output provided seems to work correctly in the environment you tested (the local machine, I believe).

Also, I understand that you always want those libs to publish in your private repo. If that is the case, the `--registry` is unadvised. The `--registry` option is made to overwrite what is already established. Useful for those cases when you say _"I want to do an exception this time or on this particular scenario"_, not to make it a rule.

I'd like to encourage you to make sure you have the proper configuration to, as a default, publish the libraries on your private repo. That can be done by modifying your lib's `package.json`.

I was hoping you could take a look at the npm documentation about [Preventing my package from being published on the official registry](https://docs.npmjs.com/cli/v8/using-npm/registry#how-can-i-prevent-my-package-from-being-published-in-the-official-registry)
