### ISSUE TITLE
Upgrade to Nx 16, or open version range

### ISSUE THREAD

**Issue by samuelfernandez** [bikecoders/ngx-deploy-npm#501]
Thanks for the help to align this dependency with the latest framework version :)

**Comment by rtturner** [comment]
Think all that is needed is to include `jscutlery/semver` 3.0.0 upgrade to current nx 16 PR (#498)

**Comment by dianjuar** [comment]
The update to v16 is taking longer than expected.

I wanted to let you know that we are working on it

**Comment by dianjuar** [comment]
Issue solved on [ngx-deploy-npm v6](https://www.npmjs.com/package/ngx-deploy-npm/v/6.0.0)
