### ISSUE TITLE
Fail dry run deploy if version already exists in the registry

### ISSUE THREAD

**Issue by ianldgs** [bikecoders/ngx-deploy-npm#508]
It would be nice to do something like `npm diff | grep version -q` in `--dryRun` mode, as suggested in https://github.com/npm/cli/issues/4927, to help checking if a version would fail deploy.

We do a `deploy --dryRun` in PRs, and a regular `deploy` when merged. Sometimes the merged version fails due to it already existing in the registry.

**Comment by dianjuar** [comment]
Hi @ianldgs 
Thank you for bringing up your concerns by opening this issue.

This plugin intends to be a wrapper around `npm publish`, and as the NPM team suggested, I believe other approaches can be considered to verify the current version already published on the registry.

I suggest a verification step before you run the target `deploy`. You accomplish this by creating an executor on the `project.json` to run your verification script and using the feature `dependsOn` to run that script before the deployment. This would be a pseudo config:

```json
"verify-version-already-on-the-registry": {
  "executor": "nx:run-commands",
  "options": {
    "command": "./tools/your-script-to-verify-versions.sh"
  },
},
"deploy": {
  "executor": "ngx-deploy-npm:deploy",
  "options": {
    "access": "public"
  },
  "dependsOn": ["verify-version-already-on-the-registry"]
}
```

---

Another suggestion I could bring is to use [`@jscutlery/semver`](https://github.com/jscutlery/semver) to know if you have something to deploy based on your commit messages. We use `ngx-deploy-npm` to publish `ngx-deploy-npm` (Yes, it uses itself) and `@jscutlery/semver` to determine the next version. If there is nothing to publish, `@jscutlery/semver` doesn't invoke `ngx-deploy-npm`.

You can see the real example on our [`project.json`]()

**Comment by dianjuar** [comment]
@ianldgs, Something else that we could do is add an extra param to work along with the `--dry-run` param to verify if the version is already published.

It would be something like `nx deploy YOUR_LIB --dry-run --fail-on-version-already-deployed` (we could work later on a better name). I'm proposing this because I don't think changing the original behavior of `--dry-run` on `npm publish` will be something that other users would like.

@edbzn your input is always welcome.

**Comment by dianjuar** [comment]
@edbzn your input is always welcome.

**Comment by ianldgs** [comment]
@dianjuar yes, we use jscutlery/semver. But look at this comment:

https://github.com/jscutlery/semver/issues/444#issuecomment-1558874571

I like the idea of implementing the check in this repo. It would give people one more tool to make their setup more resilient.
Even if it's a separate flag :) no strong opinion on the naming.
