### ISSUE TITLE
Support for packages that doesnt require building

### ISSUE THREAD

**Issue by xHyroM** [bikecoders/ngx-deploy-npm#516]

**Comment by dianjuar** [comment]
Hello @xHyroM
Thanks for opening an issue with your feature request.

Can you explain better why you think this is a great idea?

I just discovered that Nx has libraries that don't require build.
Can you provide some examples?
I want the library generator to look deeper into the library's behavior.

**Comment by xHyroM** [comment]
I think `--no-build` still requires to have build inside project.json but doesn't just run it.

**Comment by xHyroM** [comment]
@dianjuar

**Comment by dianjuar** [comment]
> and also could you help me more what to exactly put inside project.json? i just found https://github.com/bikecoders/ngx-deploy-npm#-configuration-file- but its for workspace.json
> 
> also pnpm nx generate ngx-deploy-npm:install throws  There is no publishable libraries in this workspace

ngx-deploy-npm was not designed for projects that don't require a build process, `pnpm nx generate ngx-deploy-npm: install` will look at all the projects in your workspace and filter out the ones that don't need a build. That was intended only to configure the publishable ones because, in Nx, you can have projects that are not publishable.

I guess that we need to do a better job of detecting the publishable projects and not base the criteria on if they are buildable or not.

To work around that problem, you will need to create the configuration by hand. 

---

Also, `workspace.json` in the docs is referring to the `project.json`. I need to update the documentation as well.

**Comment by dianjuar** [comment]
> I read in nx documentation that package.json and project.json are merged and it creates full project information.

I didn't know that it was a thing. Interesting 🤔.
That explains why I didn't see any project.json in your libs.

**Comment by dianjuar** [comment]
> For now, I'm just doing what you said - adding noBuild and empty commands array for build.

That is a workaround.
- Use the `--no-build` param.
- Creating a fake build target.

---

I have everything that I need to implement the feature. The steps that I have detected so far are:

- Update the publishable projects detection in the `install` generator
  - Currently, we are basing it on if the library is [buildable](https://github.com/bikecoders/ngx-deploy-npm/blob/main/packages/ngx-deploy-npm/src/generators/install/utils/is-a-lib.ts#LL3C35-L3C35).
- According to your feedback, the `deploy` target requires a build process.
  - We need to update that to make it optional. Providing the `--no-build` parameter for non-buildable libraries is nonsense.

Also, it would be interesting if we create a [integration test](https://github.com/bikecoders/ngx-deploy-npm/tree/main/e2e/ngx-deploy-npm-e2e/integration) to track those kind of projects.

**Comment by dianjuar** [comment]
@xHyroM, would you like to test this functionality on the next RC (Release Candidate) Version of `ngx-deploy-npm`?

`ngx-deploy-npm@7.1.0-rc.1` is still a work in progress and already has [significant changes](https://github.com/bikecoders/ngx-deploy-npm/pull/527/files).

I want to test in a real-world scenario and ensure everything looks good before launching the next minor version (V7.1.0).

**Comment by xHyroM** [comment]
Okay, i'll try. Thanks :heart:

**Comment by dianjuar** [comment]
@xHyroM I haven't forgotten about this change.

Just that the changes are massive. We are planning on making the experimental release on ngx-deploy-npm@8.0.0-rc.1
