### ISSUE TITLE
Add support for Nx v19

### ISSUE THREAD

**Issue by dgonzalezr** [bikecoders/ngx-deploy-npm#598]
The current version of `ngx-deploy-npm` does not support the latest version of Nx

![CleanShot 2024-05-28 at 13 52 07@2x](https://github.com/bikecoders/ngx-deploy-npm/assets/328492/5d784548-f938-4304-80cd-5b2ffd9dab3e)

We can see the [Nx versions allowed here](https://github.com/bikecoders/ngx-deploy-npm/blob/main/packages/ngx-deploy-npm/package.json#L12). Any chance to add support for Nx 19 soon?

**Comment by dianjuar** [comment]
Hello @dgonzalezr, good to see you again.
As you mentioned, some work is required to ngx-deploy-npm to support Nx v19.

In the meantime, you can apply a well-known solution to solve [this exact issue](
https://github.com/bikecoders/ngx-deploy-npm/issues/454#issuecomment-1375883554).
In your `package.json`, add this line:
```json
  "resolutions": {
    "@nrwl/devkit": "^YOUR.CURRENT.VERSION"
  }
```

I know that this is not ideal, but it is an easy-to-apply workaround.

---

> Any chance to add support for Nx 19 soon?

I would say that in probably 2weeks we will add support for Nx19.

**Comment by dianjuar** [comment]
@dgonzalezr [ngx-deploy-npm@8.2.0](https://www.npmjs.com/package/ngx-deploy-npm/v/8.2.0) supports Nx v19.

Feel free to open the issue again if the issue persists.
