### ISSUE TITLE
[Feature] Is it possible to commit version change on git, using a simple flag?

### ISSUE THREAD

**Issue by Sebastian-G** [bikecoders/ngx-deploy-npm#66]
Is it possible to commit version change on git, using a simple flag?

Is there any best practice about dealing with the changes if the deploy command is running in a CI/CD pipeline?

https://docs.npmjs.com/cli/v7/commands/npm-version

NPM version is automatically committing the change after patching the version, I would love to use this feature on the deploy command.

Is this feature already contained? And it is only mandatory to `git push --tags`?

**Comment by dianjuar** [comment]
Hi @Sebastian-G.
I'm glad that you brought that subject to the table.

I can understand that the version managing of a package could be a difficult task and for that reason, we decide to exclude it from the responsibilities of this builder/plugin. We explain it on the [documentation](https://github.com/bikecoders/ngx-deploy-npm#version-bumping).

Something that you can do tough, is you manage the strategy of versioning that you prefer (that better suits you) and use the option [`--package-version`](https://github.com/bikecoders/ngx-deploy-npm#--package-version) to publish the version that your strategy wants.

---

It really depends on my opinion of convention, culture, QA and, infrastructure to achieve true automation.

If you are looking for a tool I think your best bet is [semver](https://github.com/jscutlery/semver).

---

I have a slide to explain how we are going to manage that aspect to my coworkers, it might inspire you -> [quality-on-project](https://slides.com/diegojuliao/quality-on-project)
