### ISSUE TITLE
Add option to check existing package version before publishing

### ISSUE THREAD

**Issue by Romain7495** [bikecoders/ngx-deploy-npm#666]
# Add option to check existing package version before publishing

## Description
When publishing packages to npm, especially in CI/CD environments, we sometimes encounter 403 errors when trying to republish an existing version. This is particularly common with private registries (like GitLab's).

This feature request proposes adding a new option `checkExisting` that would:
- Check if the package version already exists in the registry before attempting to publish
- Skip the publish step if the version already exists
- Provide clear feedback to the user about skipped publications

## Proposed Solution
Add a new optional flag `checkExisting` (default: false) that would:
1. Read package.json for name and version
2. Query npm registry using `npm view ${packageName}@${version}`
3. Skip publishing if version exists
4. Continue with publish if version doesn't exist

Example usage:
```
{
  "deploy": {
    "executor": "@ngx-deploy-npm:deploy",
    "options": {
      "checkExisting": true
    }
  }
}
```

## Benefits
- Prevents CI/CD pipeline failures due to 403 errors on version conflicts
- Provides clearer feedback when versions already exist
- Maintains backward compatibility (opt-in feature)
- Useful for monorepos where package versions might already exist

## Implementation Notes
- No breaking changes
- Fully backward compatible (disabled by default)
- Includes unit tests
- Includes documentation updates

## Related Issues/PRs
N/A

## Additional Context
This is particularly useful in CI/CD environments where:
- Multiple pipelines might try to publish the same version
- Private registries are used (GitLab, Artifactory, etc.)
- Version conflicts need to be handled gracefully

**Comment by dianjuar** [comment]
Thank you for opening an issue and a pull request. As a maintainer, I appreciate this, as it is quite rare.

---

This is very similar to #508.

---

Let's engage in a thoughtful discussion about the behavior of this new flag.

I mostly agree with the proposed solution, but I disagree with step 3: __Skip publishing if a version exists__.

I believe it should offer flexibility to either trigger an error or issue a warning, as you suggested:

```sh
nx deploy my-lib --check-existing="warning"
# or
nx deploy my-lib --check-existing="error"
```

This approach would provide developers with the adaptability they need, allowing them to choose how to handle the situation based on their specific workflow needs.

---

@ianldgs Your thoughts are welcome.

**Comment by Romain7495** [comment]
@dianjuar I just updated the PR with your use case https://github.com/bikecoders/ngx-deploy-npm/pull/667

Initially I didn't implement this because in my case, gitlab was already throwing an error when version already exists (when we try to publish). But I prefer this solution as well, to let the user choose

**Comment by Romain7495** [comment]
Hi @dianjuar, I’ve pushed a new commit that should address the feedback. Feel free to suggest further adjustments if needed.
I followed this feedback:
```
nx deploy my-lib --check-existing="warning"
# or
nx deploy my-lib --check-existing="error"
```

**Comment by ianldgs** [comment]
@dianjuar yeah, indeed it would solve #508.

I like it!
