### ISSUE TITLE
Adding an option `--projects` for init schematic

### ISSUE THREAD

**Issue by edbzn** [bikecoders/ngx-deploy-npm#71]
Would be great to be able to select projects we want to publish when running init schematic by adding an option `--projects= project-a, project-b`, what do you think?

**Comment by dianjuar** [comment]
@edbzn this is something that I have thought about a lot.

Currently, if you want to add `ngx-deploy-npm` to another library it will overwrite all your current configuration on your `workspace.json` 😞. Also, if you want for some reason, don't add the `deploy` architect/target to a certain library it's not possible right now. 

This option is a need when you have a big workspace.

**Comment by dianjuar** [comment]
@edbzn I really like your contributions, your contributions push this project in a good direction 👍
