### ISSUE TITLE
--no-build flag doesn't work

### ISSUE THREAD

**Issue by talef-perim81** [bikecoders/ngx-deploy-npm#74]
I am trying to run this command inside an nx project:
`nx run-many --all --target=deploy --no-build`
But the `--no-build` flag wont pass to the command, but if I pass `--noBuild` it does work.

**Comment by dianjuar** [comment]
Hi @talef-perim81.
I would take a look late today at this.

Thank you for reporting your problem.

**Comment by dianjuar** [comment]
`no-build` has been deprecated on V8.0.0.

This issue can be considered as solved.
